### ISSUE TITLE
Chunk loading issues with Iris+Sodium present

### ISSUE THREAD

**Issue by Diplotomodon** [2Retr0/BedrockWaters#10]
![image](https://user-images.githubusercontent.com/86527037/149554373-55ffdb13-6adb-49ff-9a3d-bb2938d59a0a.png)

Random chunks in the world will refuse to load when both Iris/Sodium (latest release) and Bedrock Waters are installed (see above attachment for a good example). Issue persists when chunks are reloaded or updated, or even if the client is reloaded entirely.

**Comment by Treetrain1** [comment]
This also happens for me too. About 25% of the chunks don't load, but it appears that the caves underneath generate.

**Comment by Hax165** [comment]
Can confirm. Most chunks with water in them are invisible when paired with the new version of Sodium (sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14)

**Comment by 2Retr0** [comment]
Fixed with version 1.6.2!
