### ISSUE TITLE
Bug fix water does not match biome blend settings 1 17 1

### ISSUE THREAD

**Issue by MiFliK** [2Retr0/BedrockWaters#13]
![image](https://user-images.githubusercontent.com/80956290/151988488-e32aa5d0-8afb-4003-b3a9-b262ef5c2f4e.png)
I know this bug was fixed in 1.18
The problem is that version 1 18 is quite demanding and not stable, and so far there is no full version of sodium for 1 18
Me and many other people can't play on 118 because of lag
Even with powerful PCs

It would be great if this issue was fixed.

What should the water transition look like
![2022-02-01_17 39 09](https://user-images.githubusercontent.com/80956290/151989016-6b0b939b-263e-4b60-8920-2b61bf882202.png)
?

**Comment by 2Retr0** [comment]
Sorry for the late reply! At this time, I am not planning to update the mod for 1.17--Sodium has been released for 1.18 now, however, and I've just released the 1.18.2 version of this mod on CurseForge!
