### ISSUE TITLE
Incompatibility with Torrid Vision

### ISSUE THREAD

**Issue by f-raZ0R** [2Retr0/BedrockWaters#2]
This mod, and Torrid Vision, are incompatible, as their mixins aren't compatible.

**Comment by 2Retr0** [comment]
Yeah one of the mixins this mod has targets the class dealing with rendering underwater/lava fog so I could see how there can be an incompatibility with Torrid Vision. Admittedly, that particular mixin I made is pretty messy and overreaches what it needs to touch, so I may try to simplify it in the future.
