### ISSUE TITLE
Crash on startup with Iris and Sodium, if MemoryLeakFix is installed

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [2Retr0/BedrockWaters#21]
**MC** 1.19.2
**FAPI** 0.61.0
**BedrockWaters** 1.7.0
**[MemoryLeakFix](https://www.curseforge.com/minecraft/mc-mods/memoryleakfix)** 0.7.0
**[Sodium](https://www.curseforge.com/minecraft/mc-mods/sodium)** 0.4.4
**[Iris](https://www.curseforge.com/minecraft/mc-mods/irisshaders)** 1.3.1

To reproduce simply install all 4 mods and run the game.

I suspect the issue is on MemoryLeakFix's side, so I reported it to them as well: https://github.com/fxmorin/MemoryLeakFix/issues/46

But, in case I'm wrong, also reporting here.

Logs: https://gist.github.com/Footage2-Amply-Pounce/3051de600d0a701428aa60728e3d7409

**Comment by 2Retr0** [comment]
Turns out it's a Mixin incompatibility with Iris as described in #22 which is now (hopefully) fixed in version 1.7.1!
