### ISSUE TITLE
Crash on entering world with Iris

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [2Retr0/BedrockWaters#22]
**MC** 1.19.2
**FAPI** 0.61.0
**BedrockWaters** 1.7.0
**[Sodium](https://www.curseforge.com/minecraft/mc-mods/sodium)** 0.4.4
**[Iris](https://www.curseforge.com/minecraft/mc-mods/irisshaders)** 1.3.1

When BedrockWaters is installed together with Iris, the game launches fine, but crashes upon entering a world. Having no actual shaderpacks doesn't change anything. Installing Indium also doesn't help.

Might be related to #21.

Logs: https://gist.github.com/Footage2-Amply-Pounce/adb05c30895ba79093b84a3e2d6fc546

**Comment by 2Retr0** [comment]
Turns out there was a Mixin incompatibility with Iris. I've managed to fix it (hopefully) with version 1.7.1!
