### ISSUE TITLE
Invisible chunks, lots of "java.lang.IllegalStateException: stream has already been operated upon or closed" and errors mentioning Sodium, crash after some time

### ISSUE THREAD

**Issue by Timolino456** [2Retr0/BedrockWaters#23]
I tested it with v1.7.2 now and it's still happening, so here you go:

Screenshot:
![2022-09-18_13 48 47](https://user-images.githubusercontent.com/38137599/190900658-d609cfee-a637-46ac-a89b-db0e736e15d7.png)

Log: https://mclo.gs/VpsD7cL
I do have a lot of mods installed as you can see in the log, but the errors do mention Sodium. When disabling Bedrock waters, this doesn't happen anymore.
Edit: I have tried removing Colormatic as there were GitHub issues that mentioned it causing problems, but it didn't change anything, the game crashed again as soon as I reentered the world.

**Comment by 2Retr0** [comment]
Thanks! I've fixed the issue with version 1.7.3.
