### ISSUE TITLE
Option to disable the fog feature?

### ISSUE THREAD

**Issue by VHSJayden** [2Retr0/BedrockWaters#25]
Hey! I love your mod! My only request is if there was an option to config/disable the fog feature.

**Comment by WerDei** [comment]
I second this. This mod would benefit greatly from some config options. 
Underwater fog looks nice the first few times, but is very unpractical in the long run

**Comment by 2Retr0** [comment]
Will add configuration support sometime in the future!

**Comment by ghost** [comment]
> My only request is if there was an option to config/disable the fog feature.

I created a fork and removed the fog feature. I'm not a mod developer, thus I removed it very sloppily. But, I did some quick testing and it seems to have worked.

<img src="https://github.com/lavndor/fork-BedrockWaters/assets/88053191/3338b8c1-405c-48e7-a37d-f2662dc01c70" width="50%">
<img src="https://github.com/lavndor/fork-BedrockWaters/assets/88053191/ba54c1ab-2b26-4ca6-a63f-88230fcf122c" width="50%">

Can download [here](https://github.com/lavndor/fork-BedrockWaters/releases/tag/1.7.7%2B1.20.1-less_fog) or compile it yourself from my [branch](https://github.com/lavndor/fork-BedrockWaters/tree/less_fog) if you don't trust my binary.

**Comment by 2Retr0** [comment]
Added configuration support in version 1.8.0! Seriously sorry for the lengthy wait!
