### ISSUE TITLE
1.7.7 (for 1.20 and 1.20.1) uses TravellersToasts configuration

### ISSUE THREAD

**Issue by ghost** [2Retr0/BedrockWaters#33]
go to in the mod's files, then go to the en_us.json file in the lang folder and you'll notice this mod uses TravellersToasts configuration instead of BedrockWaters configuration.

If you go to BedrockWaters config in the game in the mods list, you'll see that it uses TravellersToasts configuration instead of BedrockWaters configuration even in the game.

**Comment by 2Retr0** [comment]
Yeah, sorry about that. This has been fixed with version 1.8.0!
