### ISSUE TITLE
incompatibility with sodium 0.5.0

### ISSUE THREAD

**Issue by ghost** [2Retr0/BedrockWaters#35]
crashes on world startup
used mods
sodium-fabric-mc1.20.1-0.5.0
bedrockwaters-1.7.7+1.20.1
fabric-api-0.86.1+1.20.1(1)
how to check
load game with mod sodium 0.5.0 and bedrock water
and fabric api
create a new world or enter an existing one get a crash when starting the world

**Comment by 2Retr0** [comment]
Sodium version 0.5.x compatibility has been fixed in version 1.8.0!
