### ISSUE TITLE
Crash on World Load/Incompatible with Sodium 0.5.0

### ISSUE THREAD

**Issue by SAJewers** [2Retr0/BedrockWaters#36]
Attempting to Load a world with the latest versions BedrockWaters and Sodium causes minecraft to crash.

[crash-2023-08-06_13.57.10-client.txt](https://github.com/2Retr0/BedrockWaters/files/12270090/crash-2023-08-06_13.57.10-client.txt)

**Comment by shardeex** [comment]
Same problem.

**Comment by ghost** [comment]
same

**Comment by Sputnik1996** [comment]
Same problem here with BedrockWaters 1.7.7 and Sodium 0.5.2
Let's pray for Dev to have some free time to spare...

**Comment by TheKveilan** [comment]
I really hope for an update

**Comment by 2Retr0** [comment]
Sodium version 0.5.x compatibility has been fixed in version 1.8.0!
