### ISSUE TITLE
Opaque flowing water

### ISSUE THREAD

**Issue by Jab125** [2Retr0/BedrockWaters#38]

**Comment by MaxenceDC** [comment]
I have the same issue.

**Comment by LitsyPorksulum** [comment]
yep, i thinks its cuz of sodium

**Comment by 2Retr0** [comment]
> yep, i thinks its cuz of sodium

Yeah, Sodium uses the alpha field for a color for lighting information. As a quick fix, biome-specific water opacity (and therefore the resource pack) will be disabled when using Sodium. These changes have been reflected in version 1.8.0!
