### ISSUE TITLE
Bug with the transition between biomes on the water

### ISSUE THREAD

**Issue by MiFliK** [2Retr0/BedrockWaters#8]
The problem is that the transition between water biomes looks too harsh
It doesn't look like this on the hip
it should look like this only on a swamp in old versions

Idea Make it only applied to swamp biomes And it is better to make this function optional in the mod menu
since new versions of bedrock have not had this since update 1.13 aquatic

photo water And bug imgur https://imgur.com/a/Zubg8sI

**Comment by 2Retr0** [comment]
Sorry for the late response, since version 1.6.0 this issue has been fixed!
